# Generated by Django 3.2.9 on 2021-11-16 13:58

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('pins', '0002_save'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='save',
            unique_together={('pin_id', 'user_id')},
        ),
    ]
