# Generated by Django 3.2.9 on 2021-11-16 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pins', '0004_history'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pin',
            name='topic',
        ),
        migrations.AddField(
            model_name='pin',
            name='topic',
            field=models.ManyToManyField(blank=True, to='pins.Topic'),
        ),
    ]
