# Generated by Django 3.2.9 on 2021-11-16 14:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('pins', '0007_comment_reply'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='pin_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='pins.pin', verbose_name='Pin'),
        ),
        migrations.AlterField(
            model_name='imagereact',
            name='pin_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='pins.pin', verbose_name='Pin'),
        ),
        migrations.AlterField(
            model_name='reply',
            name='comment_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='pins.comment', verbose_name='Comment'),
        ),
        migrations.CreateModel(
            name='CommentReact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='pins.comment', verbose_name='Comment')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
            options={
                'unique_together': {('comment_id', 'user_id')},
            },
        ),
    ]
