# Generated by Django 3.2.9 on 2021-11-16 19:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pins', '0008_auto_20211116_1449'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='imagereact',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='imagereact',
            name='pin_id',
        ),
        migrations.RemoveField(
            model_name='imagereact',
            name='user_id',
        ),
        migrations.RemoveField(
            model_name='board',
            name='image',
        ),
        migrations.DeleteModel(
            name='CommentReact',
        ),
        migrations.DeleteModel(
            name='ImageReact',
        ),
    ]
