# Generated by Django 3.2.9 on 2021-11-16 19:44

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('pins', '0010_pin_react'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pin',
            name='react',
            field=models.ManyToManyField(related_name='react', to=settings.AUTH_USER_MODEL),
        ),
    ]
