# Generated by Django 3.2.9 on 2021-11-21 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pins', '0016_alter_pin_react'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pin',
            name='website',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
