# Generated by Django 3.2.9 on 2021-11-21 11:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pins', '0017_alter_pin_website'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pin',
            old_name='creator_id',
            new_name='creator',
        ),
    ]
