# Generated by Django 3.2.9 on 2021-11-16 15:02

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_message'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='followees',
            field=models.ManyToManyField(related_name='_accounts_user_followees_+', through='accounts.Following', to=settings.AUTH_USER_MODEL, verbose_name='following'),
        ),
    ]
