# Generated by Django 3.2.9 on 2021-11-16 16:12

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_alter_user_followees'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='followees',
        ),
        migrations.AddField(
            model_name='user',
            name='followers',
            field=models.ManyToManyField(blank=True, related_name='_accounts_user_followers_+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='user',
            name='following',
            field=models.ManyToManyField(blank=True, related_name='_accounts_user_following_+', to=settings.AUTH_USER_MODEL),
        ),
    ]
