# Generated by Django 3.2.9 on 2021-11-16 16:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_auto_20211116_1612'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Following',
        ),
    ]
